#!/bin/bash

function check {
  if [ $retVal -ne 0 ]
  then
    echo "Failed, aborting commit. Please run \e[1mmake pretty\e[0m]."
    exit 1
  fi
}

echo Validate HTML
node_modules/html-validate/bin/html-validate.js "src/main/webapp/**/*.html"
retVal=$?
check

echo Validate CSS
node_modules/css-validator/bin/css-validator src/main/webapp/*.css src/main/webapp/view/*.css src/main/webapp/lectures/*.css
retVal=$?
check

echo Validate JavaScript
node_modules/eslint/bin/eslint.js src/**/*.js
retVal=$?
check

echo Everything looks good, continuing with push
exit 0
