#!/bin/bash

function check {
  if [ $retVal -ne 0 ]
  then
    echo "Failed, aborting commit"
    exit 1
  fi
}

echo Maven Build
mvn clean
mvn package
retVal=$?
check

echo Prettifying
make pretty

echo Validate HTML
node_modules/html-validate/bin/html-validate.js src/main/webapp/*.html
retVal=$?
check

echo Validate CSS
node_modules/css-validator/bin/css-validator src/main/webapp/*.css
retVal=$?
check

echo Validate JavaScript
node_modules/eslint/bin/eslint.js src/**/*.js
retVal=$?
check

echo Everything looks good, continuing with commit
exit 0